karpenter 추가
team-xquare/xquare-infrastructure-global pull request #15
Opened 2023-08-21 05:59 UTC by pokabook

2023-08-21 07:36 UTC, rlaisqls requested changes

2023-08-21 07:36 UTC, rlaisqls commented on modules/eks-cluster/modules/karpenter/main.tf
> +  version             = "v0.29.2"
이거 repository https://team-xquare.github.io/k8s-resource 이걸로 바꾸고
chart랑 version karpenter 1.16.1로 변경 ㄱㄱ 배포해놨음

2023-08-21 07:36 UTC, rlaisqls commented on modules/eks-cluster/modules/karpenter/main.tf
> +  version             = "v0.29.2"
username password 필요 없음

2023-08-21 07:54 UTC, rlaisqls requested changes

2023-08-21 07:54 UTC, rlaisqls commented on modules/eks-cluster/modules/karpenter/main.tf
> +  version             = "v0.29.2"
https://team-xquare.github.io/k8s-resource 
karpenter 0.30.0
이걸로 변경 ㄱㄱ

2023-08-21 22:29 UTC, pokabook commented on modules/eks-cluster/modules/karpenter/main.tf
> +  version             = "v0.29.2"
ㅇㅋ

2023-08-21 23:31 UTC, rlaisqls commented on modules/eks-cluster/modules/karpenter/main.tf
> +  version             = "v0.29.2"
repository도 https://team-xquare.github.io/k8s-resource 이걸로 바꿔줘

2023-08-22 00:50 UTC, rlaisqls commented on modules/eks-cluster/modules/karpenter/main.tf
> +  repository          = "https://team-xquare.github.io/k8s-resource "
공백머임

2023-08-22 00:51 UTC, pokabook commented on modules/eks-cluster/modules/karpenter/main.tf
> +  repository          = "https://team-xquare.github.io/k8s-resource "
복사 잘못한듯

2023-08-22 00:56 UTC, rlaisqls approved these changes
시간나면 cloud config 좀 봐주시오..

2023-08-22 01:02 UTC, merged